
Test assert.eql(FizzBuzz dividedByThree(1), 1)
Test assert.eql(FizzBuzz dividedByThree(3), "Fizz")
Test assert.eql(FizzBuzz dividedByFive(1), 1)
Test assert.eql(FizzBuzz dividedByFive(5), "Buzz")
Test assert.eql(FizzBuzz dividedByFithteen(1), 1)
Test assert.eql(FizzBuzz dividedByFithteen(15), "FizzBuzz")
Test assert.eql(FizzBuzz shout(1),1)
Test assert.eql(FizzBuzz shout(3),"Fizz")
Test assert.eql(FizzBuzz shout(5),"Buzz")
Test assert.eql(FizzBuzz shout(15),"FizzBuzz")
